build:
	gcc sys_call_one.c -o sys_call_one
	gcc sys_call_two.c -o sys_call_two
	gcc sys_call_three.c -o sys_call_three
	gcc process_one.c -o process1
	gcc process_2.c -o process2
	gcc thread_1.c -o thread1
	gcc thread_2.c -o thread2
	gcc thread_3.c -o thread3

