build:
	gcc 4_client.c -o client4 -lrt
	gcc 4_server.c -o server4 -lrt
	gcc q1_stack.c -o stack1 -lpthread
	gcc 3_stack_mutex.c -o 3mutex -lpthread
	gcc q5_sender.c -o 5sender -lrt
	gcc q5_receiver.c -o 5receiver -lrt



